version: '3.8'
services:
  mongo:
    image: mongo:6
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: practica
  app:
    build: .
    ports:
      - 8080:8080
    environment:
      - MONGO_URL=mongodb://mongo:27017/practica
      - PORT=8080
    depends_on:
      - mongo